import { config } from './config.js';

export function botInfoPageText(): string {
  return [
    '# Scrum Master Bot · Projektübersicht',
    '',
    'Der Bot unterstützt Joline, David und Duy bei der täglichen Projektdokumentation, Arbeitszeiterfassung, Meetings, Aufgaben, Blockern, Entscheidungen und Wochenberichten.',
    '',
    '## Wichtigste Regeln',
    '- **Daily zuerst, danach Projektarbeit.** Das Daily wird unmittelbar vor dem eigenen Arbeitsbeginn erstellt.',
    '- Reguläre Projekttage sind **Montag bis Freitag**. Am Wochenende ist kein Daily Pflicht.',
    '- Nach einem Daily startet die Arbeitszeiterfassung automatisch. Zum Tagesende bitte **/feierabend** nutzen.',
    '- Alte, bereits vorhandene Dailies bleiben erhalten und werden weiterhin für den Wochenbericht gelesen.',
    '- Das freiwillige Aufgabenboard ist nur eine Planungshilfe und keine Voraussetzung für ein gültiges Daily.',
    '',
    '## Bot-Zeiten',
    '**Online:** täglich von **08:00 bis 23:00 Uhr**',
    '**Offline:** täglich von **23:00 bis 08:00 Uhr**',
    '',
    'Während der Offline-Zeit reagieren Slash Commands, Buttons und Erinnerungen nicht.',
    'Wenn du nach 23:00 Uhr weiterarbeiten möchtest, erstelle dein Daily noch vor 23:00 Uhr. Falls die tatsächliche Endzeit erst nach dem Herunterfahren liegt, trage sie am nächsten Morgen mit **/arbeitszeit nachtragen** korrekt nach.',
    '',
    '## Daily Scrum',
    '**/daily** startet den Daily-Dialog oder die Abmeldung.',
    'Der Bot fragt:',
    '1. Was wurde seit dem letzten Daily erledigt?',
    '2. Was möchtest du heute machen?',
    '3. Gibt es Blocker?',
    '4. An welchem Branch arbeitest du und muss noch etwas gepusht werden?',
    '',
    'Der fertige Daily wird im persönlichen Daily-Forum gespeichert. Ein angefangenes, aber nicht abgesendetes Daily zählt nicht.',
    '',
    '**Erinnerungen:**',
    '- 09:00 Uhr · Daily-Runde wird geöffnet',
    '- 15:00 Uhr · erste Erinnerung bei fehlendem Daily oder fehlender Abmeldung',
    '- 20:00 Uhr · zweite Erinnerung',
    '- 08:05 Uhr am Folgetag · Prüfung auf fehlende Dokumentation des vorherigen Arbeitstags',
    '',
    '## Daily nachträglich korrigieren',
    '**/daily-bearbeiten** öffnet dein bereits abgesendetes Daily von heute erneut. Der vorhandene Beitrag wird geändert, es entsteht kein zweites Daily.',
    '',
    '## Arbeitszeit',
    'Nach dem Absenden eines Dailys beginnt automatisch eine Arbeitszeitsitzung.',
    '- **/feierabend** · beendet den heutigen Arbeitstag und fragt die Pausenzeit ab',
    '- **/arbeitszeit status** · zeigt deine letzten gespeicherten Arbeitszeiten',
    '- **/arbeitszeit nachtragen** · ergänzt oder korrigiert einen vergangenen Arbeitstag',
    '',
    'Nachgetragene Zeiten können als **genau** oder **geschätzt** gekennzeichnet werden. Für alte Dailies ohne gespeicherte Arbeitszeit werden keine Zeiten erfunden.',
    '',
    '## Abmelden',
    'Wenn du an einem regulären Projekttag nicht arbeiten kannst, wähle bei **/daily** „Nein, abmelden“.',
    'Mögliche Gründe sind **Krankheit**, **Termin** oder **Anderes**. Eine gültige Abmeldung ersetzt für diesen Tag das Daily und verhindert weitere Daily-Erinnerungen.',
    'Bei Krankheit erinnert der Bot zusätzlich an die Krankmeldung im bib-Intranet.',
    '',
    '## Push-Erinnerung',
    'Wenn im Daily **Noch zu pushen: Ja** angegeben wurde, prüft der Bot regelmäßig den dokumentierten Status. Nach ungefähr 6 Stunden kann einmalig eine Erinnerung im Daily-Thread erscheinen.',
    'Der Bot kontrolliert **nicht GitHub** und hat keinen Zugriff auf das private Hauptprojekt-Repository.',
    '',
    '## Wochenbericht',
    'Der automatische Wochenbericht wird **freitags ab 14:00 Uhr alle 30 Minuten geprüft**. Er wird erst erstellt, wenn Freitag für alle drei Teammitglieder abgeschlossen dokumentiert ist:',
    '- Daily **und** abgeschlossene Arbeitszeit',
    '- oder gültige Abmeldung',
    '',
    'Der Wochenbericht verwendet weiterhin auch alle alten Discord-Dailies ab Beginn der Erfassung.',
    'Er berücksichtigt unter anderem Tätigkeiten, Arbeitszeiten, Abmeldungen, Blocker sowie dokumentierte Meeting-Inhalte.',
    'Meeting-Protokolle, Aufgaben und Entscheidungen erscheinen nur, wenn tatsächlich etwas dazu eingetragen wurde.',
    '',
    '**Wochenbericht-Befehle:**',
    '- **/wochenbericht vorschau** · aktuellen Bericht privat ansehen',
    '- **/wochenbericht erstellen** · Bericht manuell neu erzeugen',
    '- **/wochenbericht freigeben** · neuesten Bericht als freigegeben markieren',
    '- **/wochenbericht export** · aktuellen Bericht als Markdown-Datei exportieren',
    '',
    '## Meetings',
    `Neue Meetings werden mit **/meeting** in <#${config.meetingCreateChannelId}> erstellt.`,
    'Als Ort stehen **Discord Voice**, **Alfaview** oder **Anderer Link** wie Microsoft Teams zur Verfügung.',
    'Titel, Datum, Uhrzeit, Dauer und Agenda werden dokumentiert. Vergangene Meetings können mit **/meeting-nachtragen** ergänzt werden.',
    '',
    'Unter einem Meeting stehen die Aktionen **Protokoll**, **Aufgabe** und **Entscheidung** zur Verfügung. Diese Inhalte können in den Wochenbericht einfließen.',
    '',
    '## Freiwilliges Aufgabenboard',
    '**/task** verwaltet das optionale To-Do / Doing / Done-Board.',
    '- **/task add** · Aufgabe anlegen',
    '- **/task board** · komplettes Board anzeigen',
    '- **/task meine** · eigene offene Aufgaben anzeigen',
    '- **/task move** · eigene Aufgabe verschieben',
    '- **/task fortschritt** · freiwilligen Fortschritt von 0–100 % setzen',
    '- **/task löschen** · eigene Aufgabe aus dem Board entfernen',
    '',
    'Nach einem Daily können die unter „Heute“ eingetragenen Punkte freiwillig ins Board übernommen werden.',
    '',
    '## Blocker',
    'Blocker aus Dailies werden als offene Blocker übernommen.',
    '- **/blocker add** · Blocker manuell erfassen',
    '- **/blocker offen** · offene Blocker anzeigen',
    '- **/blocker lösen** · eigenen Blocker als gelöst markieren',
    '',
    '## Entscheidungen',
    '- **/entscheidung add** · wichtige Projektentscheidung mit optionaler Begründung dokumentieren',
    '- **/entscheidung liste** · dokumentierte Entscheidungen anzeigen',
    '',
    '## Status und Hilfe',
    '- **/scrum status** · heutigen Daily-/Abmeldestatus des Teams anzeigen',
    '- **/scrum heute** · Alias für den heutigen Scrum-Status',
    '- **/status** · technische Bot- und Channel-Konfiguration prüfen',
    '- **/info** · diese Info-Seite bewusst neu veröffentlichen bzw. aktualisieren',
    '- **/test** · geplante Bot-Aktionen manuell testen, nur für Personen mit „Server verwalten“',
    '',
    'Die Info-Seite wird **nicht automatisch beim morgendlichen Bot-Start neu gepostet**. Dadurch entstehen keine täglichen Duplikate.',
    '',
    '## Daten & Neustarts',
    'Abgesendete Dailies und Abmeldungen liegen in Discord. Projektstatus, Arbeitszeiten und Meeting-Historie werden zusätzlich persistent gespeichert. Der tägliche Shutdown löscht diese Daten nicht.',
    '',
    `_Reguläre Auswertung ab ${config.trackingStartDate}. Bitte wichtige Wochenberichte vor der Weitergabe kurz prüfen._`
  ].join('\n');
}
