import { config } from './config.js';

export function botInfoPageText(): string {
  return [
    '# Schule · bib-Projektregeln',
    '',
    '**Grundlage dieser Übersicht:** Projekt-Infos für Studierende V2.6 (Stand Juli 2018), Projekt-Checkliste V1.2 (Stand Mai 2017), Doku-Richtlinie für IT-Projekte V2.4, Projektbewertung IT 2020, Tätigkeitsbericht-Muster sowie das Formular „Aufgabenverteilung und Zeugnistext“.',
    'Die Unterlagen enthalten teilweise ältere Versionsstände. Bei abweichenden aktuellen Terminen oder Verfahren gelten die aktuellen Angaben im bib-Intranet und die Absprachen mit dem projektbetreuenden Dozenten (PbD).',
    '',
    '## Projektphase und Ansprechpartner',
    '- Ansprechpartner des Projektteams im bib ist grundsätzlich der **projektbetreuende Dozent (PbD)**.',
    '- Die für die Klasse geltenden Projekttermine stehen im bib-Intranet.',
    '- Die Projektzeit kann nicht einfach verlängert werden. Wesentliche Projektarbeiten sollen innerhalb der vorgesehenen Projektlaufzeit erledigt werden.',
    '- Projektbedingte Unterrichtsfehlzeiten nach Ende der Projektphase sind laut bereitgestellter Projekt-Info grundsätzlich unentschuldigt; als Ausnahme wird die Projektabnahme genannt.',
    '',
    '## Meldepflichten während des Projekts',
    '- Am ersten Projekttag ist dem PbD die Projektaufnahme zu melden. In der bereitgestellten Projekt-Info werden außerdem Erreichbarkeit, Ansprechpartner im Projektumfeld und eventuelle Änderungen der Aufgabenstellung genannt.',
    '- **Jeden Freitag** ist ein Wochenbericht an den PbD vorgesehen.',
    '- Im Wochenbericht müssen die **Arbeitszeiten und Tätigkeiten jedes Teammitglieds individuell** hervorgehen. Die Berichte dokumentieren Anwesenheit und Leistung.',
    '- Änderungen oder Nachträge zum Projektauftrag sollen dem PbD sofort mitgeteilt und möglichst vorher abgestimmt werden.',
    '- Der PbD soll einen groben Überblick über die Zeitplanung des Projekts haben.',
    '- Probleme, die im Projektumfeld nicht selbst gelöst werden können, sollen frühzeitig mit dem PbD besprochen werden. Nicht erst warten, bis dadurch wertvolle Projektzeit verloren geht.',
    '',
    '## Krankheit und Fehlzeiten',
    '- Laut bereitgestellter Projekt-Info muss eine Krankmeldung **am ersten Krankheitstag vor Arbeitsbeginn** beim Ansprechpartner im Projektunternehmen telefonisch oder per E-Mail erfolgen.',
    '- Gleichzeitig ist der PbD per E-Mail über die Krankheit zu informieren.',
    '- Fehlzeiten müssen zusätzlich gegenüber dem Projektunternehmen entschuldigt werden.',
    '- Ab dem **dritten Fehltag** ist laut dieser Unterlage eine Arbeitsunfähigkeitsbescheinigung sowohl dem PbD als auch dem Projektunternehmen vorzulegen bzw. zuzusenden.',
    '- Gefährdet eine längere Krankheit das Projektziel, soll mit dem PbD eine individuelle Lösung abgestimmt werden.',
    '- Für unser aktuelles Teamverfahren erinnert der Bot bei Krankheit zusätzlich an die Krankmeldung im bib-Intranet vor 08:00 Uhr. Diese Bot-Erinnerung ersetzt keine schulische oder betriebliche Meldepflicht.',
    '',
    '## Wochenbericht und Tätigkeitsnachweis',
    '- Der Wochenbericht ist kein allgemeiner Teamtext. Zeiten und Tätigkeiten müssen pro Person nachvollziehbar sein.',
    '- Das Tätigkeitsbericht-Muster sieht die Wochentage Montag bis Freitag und eine Zuordnung von Tätigkeiten sowie gegebenenfalls abweichenden Arbeitszeiten vor.',
    '- Als typische Tätigkeiten nennt das Muster unter anderem Erhebung und Analyse, Dokumentation, Test, Codierung, Besprechung, Interview und Präsentation.',
    '- Abweichungen von der regulären Arbeitszeit sollen nachvollziehbar dokumentiert werden, zum Beispiel ein Arzttermin oder eine andere zeitliche Unterbrechung.',
    '- Der Scrum-Master-Bot sammelt deshalb Dailies, echte Arbeitszeiten, Pausen, Abmeldungen, Meetings und weitere Projektdaten als Grundlage für den Wochenbericht. Er erfindet keine fehlenden Zeiten.',
    '',
    '## Projektdokumentation',
    'Die IT-Doku-Richtlinie beschreibt die Software-Projektdokumentation als **eine zusammenhängende Gesamtdokumentation aus sechs Teilen**:',
    '1. Pflichtenheft',
    '2. Entwurfsdokumentation',
    '3. Implementierungsdokumentation',
    '4. Testdokumentation',
    '5. Benutzerdokumentation',
    '6. Installationshandbuch',
    '',
    '**Formale Grundpunkte aus der Richtlinie:**',
    '- grundsätzlich DIN A4',
    '- bei gebundener Dokumentation ausreichend Bundsteg; empfohlen werden mindestens 2 cm',
    '- jeder Dokumentationsunterlage soll ein Deckblatt vorangestellt werden',
    '- die einzelnen Teile sollen inhaltlich aufeinander aufbauen und insgesamt gut nachvollziehbar sein',
    '',
    '**Pflichtenheft:**',
    '- beschreibt das **WAS**, also die vom Benutzer sichtbaren Leistungen und Anforderungen, ohne die konkrete Lösung vorwegzunehmen',
    '- bildet die verbindliche Grundlage für die folgenden Entwicklungsphasen',
    '- zu den vorgesehenen Punkten sollen Aussagen gemacht werden; nicht zutreffende Punkte werden als „entfällt“ gekennzeichnet',
    '- Muss- und Kann-Kriterien sollen unterschieden werden',
    '- zur Modellierung eignen sich unter anderem Use-Case- und Aktivitätsdiagramme',
    '- bei Datenbankprojekten ist laut Richtlinie ein ER-Modell erforderlich',
    '',
    '**Entwurfsdokumentation:**',
    '- beantwortet das **WIE** der Lösung',
    '- beschreibt das technische Modell und die für die Umsetzung relevanten Details',
    '- soll so aufgebaut sein, dass die spätere Implementierung aus dem Entwurf nachvollziehbar abgeleitet werden kann',
    '',
    '**Implementierungsdokumentation:**',
    '- dokumentiert die konkrete Realisierung, Entwicklungsumgebung, Struktur und relevante Implementierungsdetails',
    '- Quellcode und Schnittstellen sollen für Fachpersonal nachvollziehbar bleiben',
    '',
    '**Testdokumentation:**',
    '- Testaktivitäten sollen frühzeitig beginnen und parallel zur Entwicklung laufen',
    '- ein Testfall soll einen eindeutigen Bezeichner, getestete Anforderungen, Vorbedingungen, Testschritte und Eingabedaten sowie das erwartete Ergebnis enthalten',
    '- Testdurchführungen und Ergebnisse sollen protokolliert werden; Fehler und Folgemaßnahmen sind nachvollziehbar festzuhalten',
    '- auch nichtfunktionale Tests wie Last, Performanz oder unterschiedliche Systemkonfigurationen können relevant sein',
    '',
    '**Benutzerdokumentation:**',
    '- richtet sich an die tatsächliche Benutzergruppe und soll sprachlich zu deren Kenntnisstand passen',
    '- soll Gebrauch und Verhalten des Produkts verständlich erklären und darf nicht einfach Entwickler-Fachsprache voraussetzen',
    '',
    '**Installationshandbuch:**',
    '- dokumentiert die für Installation, Einrichtung und Inbetriebnahme erforderlichen Informationen',
    '',
    'Die Projektdokumentation ist ein wesentlicher Teil der Projektleistung. In der bereitgestellten Projekt-Info ist vorgesehen, dass die mit dem PbD abgestimmte Gesamtdokumentation am letzten Projekttag abgegeben wird.',
    '',
    '## Projektjahrbuch, Präsentation und Projektende',
    '- Für das Projektjahrbuch ist eine Kurzfassung der Aufgabenstellung vorgesehen. Laut Projekt-Info werden pro Team außerdem zwei Bilder eingereicht; Veröffentlichung von Text und Bildern soll mit dem Projektunternehmen abgestimmt werden.',
    '- In der letzten Projektwoche präsentiert das Team das Projekt im Projektunternehmen. Der PbD ist dazu einzuladen, und die Organisation liegt beim Projektteam.',
    '- Im Anschluss an die Projektphase ist außerdem eine Vorstellung im Rahmen des Recruiting Day vorgesehen. Stand und Präsentation fließen laut Unterlage in die Projektbewertung ein.',
    '- Am Ende der Arbeit im Projektunternehmen müssen überlassene Unterlagen, Hardware, Software, Schlüssel, Ausweise und die Projektdokumentation zurück- bzw. übergeben werden.',
    '- Bei Software gehören dazu auch erforderliche Passwörter, Bedienungshinweise und vergleichbare Informationen.',
    '- Das Team soll sicherstellen, dass dem Unternehmen der Beurteilungsbogen vorliegt und dieser an das bib zurückgegeben wird.',
    '',
    '## Aufgabenverteilung und Zeugnistext',
    '- Mit der Projektdokumentation ist laut Projekt-Info am letzten Tag der Projektphase das Formular **„Aufgabenverteilung und Zeugnistext“** abzugeben.',
    '- Das Formular dokumentiert den prozentualen Arbeitsanteil der einzelnen Teammitglieder sowie Datum und Unterschrift.',
    '- Der Zeugnistext beschreibt die Projektaufgabe und darf laut Formular maximal **160 Zeichen inklusive Leerzeichen** enthalten.',
    '- Der Bot berechnet **keine prozentualen Arbeitsanteile** aus Tasks, Dailies oder Stunden. Die tatsächliche Aufgabenverteilung wird vom Team selbst festgelegt.',
    '',
    '## Projektbewertung',
    'Das bereitgestellte Bewertungsraster für IT-Projekte umfasst insgesamt **200 Punkte**:',
    '- **Produkt / Funktionalität:** 100 Punkte = 50 %',
    '- **Dokumentation:** 40 Punkte = 20 %',
    '- **Präsentation:** 30 Punkte = 15 %',
    '- **Sonstiges / Formales:** 30 Punkte = 15 %',
    '',
    'Zum formalen Bereich gehören laut Bewertungsbogen unter anderem Projektvorbereitung, Pünktlichkeit bei Abgabeterminen und Verpflichtungen sowie selbstständiges Arbeiten. Bei der Pünktlichkeit werden ausdrücklich Tätigkeitsberichte, Dokumentationsabgaben und wöchentliche Meldungen berücksichtigt.',
    'Bei unzureichender Rechtschreibung, Zeichensetzung, Grammatik oder Ausdruck sowie bei Plagiaten können in den jeweils betroffenen Bereichen erhebliche Punktabzüge erfolgen. Bei unterschiedlichen Arbeitsanteilen oder Leistungen sind individuelle Bewertungen der Teammitglieder möglich.',
    '',
    '## Schulische Projekt-Checkliste',
    'Die bereitgestellte Checkliste nennt während und am Ende des Projekts unter anderem:',
    '- erste Projektmeldung und Erreichbarkeit',
    '- regelmäßige Wochenberichte',
    '- Pflichtenheft / Projektauftrag und weitere Dokumentation',
    '- Abstimmung und Durchführung der Projektpräsentation',
    '- Projektjahrbuch',
    '- Abgabe der Gesamtdokumentation',
    '- Formular „Aufgabenverteilung und Zeugnistext“',
    '- vollständige Übergabe im Projektunternehmen',
    '- Beurteilung durch das Unternehmen und Nachbesprechung mit dem PbD',
    '',
    '# Bot',
    '',
    '## Scrum Master Bot · Projektübersicht',
    '',
    'Der Bot unterstützt Joline, David und Duy bei der täglichen Projektdokumentation, Arbeitszeiterfassung, Meetings, Aufgaben, Blockern, Entscheidungen und Wochenberichten.',
    '',
    '## Wichtigste Teamregeln',
    '- **Daily zuerst, danach Projektarbeit.** Das Daily wird unmittelbar vor dem eigenen Arbeitsbeginn erstellt.',
    '- Die Arbeitszeit wird davon getrennt im Zeiterfassungs-Channel mit **Start / Pause / Ende** dokumentiert.',
    '- Reguläre Projekttage sind **Montag bis Freitag**. Am Wochenende ist kein Daily Pflicht.',
    '- Alte, bereits vorhandene Dailies bleiben erhalten und werden weiterhin für den Wochenbericht gelesen.',
    '- Das freiwillige Aufgabenboard ist nur eine Planungshilfe und keine Voraussetzung für ein gültiges Daily.',
    '',
    '## Bot-Zeiten',
    '**Online:** täglich ungefähr **08:05 bis 23:00 Uhr**',
    '**Offline:** täglich **23:00 bis ungefähr 08:05 Uhr**',
    '',
    'Der Server fährt um 08:00 Uhr hoch. Bis Discord-Verbindung, Slash Commands und alle Bot-Funktionen bereit sind, können einige Minuten vergehen.',
    'Die reguläre Prüfung auf fehlende Dokumentation läuft bewusst erst um **08:10 Uhr**, damit der Bot nach dem Serverstart etwas Puffer hat.',
    'Während der Offline-Zeit reagieren Slash Commands, Buttons und Erinnerungen nicht.',
    '',
    '## Daily Scrum',
    '**/daily** startet den Daily-Dialog oder die Abmeldung.',
    'Der Bot fragt:',
    '1. Was wurde seit dem letzten Daily erledigt?',
    '2. Was möchtest du heute machen?',
    '3. Gibt es Blocker?',
    '4. An welchem Branch arbeitest du und muss noch etwas gepusht werden?',
    '',
    'Der fertige Daily wird im persönlichen Daily-Forum gespeichert. Ein angefangenes, aber nicht abgesendetes Daily zählt nicht.',
    '',
    '**Daily-Erinnerungen:**',
    '- 09:00 Uhr · Daily-Runde wird geöffnet',
    '- 15:00 Uhr · erste Erinnerung bei fehlendem Daily oder fehlender Abmeldung',
    '- 20:00 Uhr · zweite Erinnerung',
    '- 08:10 Uhr am Folgetag · Prüfung auf fehlende Dokumentation des vorherigen regulären Projekttags',
    '',
    '## Daily nachträglich korrigieren',
    '**/daily-bearbeiten** öffnet dein bereits abgesendetes Daily von heute erneut. Der vorhandene Startbeitrag wird geändert; es entsteht kein zweites Daily.',
    'Bereits freiwillig ins Aufgabenboard übernommene Tasks werden dadurch nicht automatisch geändert.',
    '',
    '## Abmelden',
    'Wenn du an einem regulären Projekttag nicht arbeiten kannst, wähle bei **/daily** „Nein, abmelden“.',
    'Mögliche Gründe sind **Krankheit**, **Termin** oder **Anderes**. Eine gültige Abmeldung ersetzt für diesen Tag das Daily und verhindert weitere Daily-Erinnerungen.',
    'Bei Krankheit erinnert der Bot zusätzlich an das aktuell von uns verwendete bib-Intranet-Verfahren. Maßgeblich bleiben die schulischen und betrieblichen Regeln im Abschnitt „Schule“.',
    '',
    '## Arbeitszeit · Start / Pause / Ende',
    `Die Zeiterfassung befindet sich in <#${config.timeTrackingChannelId}>. Dort liegt eine feste Bot-Nachricht mit drei Buttons.`,
    '- **Start** · startet deine Arbeitszeit. Ein zweiter Klick startet keine zweite Zeit und meldet stattdessen, wann du bereits angefangen hast.',
    '- **Pause** · startet eine Pause. Nur die jeweilige Person bekommt privat den Button **🟠 Weitermachen** angezeigt.',
    '- **Weitermachen** · beendet die laufende Pause und summiert die Pausenzeit.',
    '- **Ende** · beendet den Arbeitstag und speichert Start, Ende, Pausen und Netto-Arbeitszeit.',
    '- Wird **Ende während einer Pause** gedrückt, beendet der Bot die laufende Pause automatisch zum gleichen Zeitpunkt und schließt danach den Arbeitstag ab.',
    '',
    'Alle Bestätigungen der Zeiterfassung sind privat, damit der Zeiterfassungs-Channel sauber bleibt.',
    'Discord bietet technisch keine orange Button-Farbe. „Weitermachen“ ist deshalb als privater Button mit 🟠-Kennzeichnung umgesetzt.',
    '',
    '**Zusätzliche Arbeitszeit-Befehle:**',
    '- **/feierabend** · Alternative zum roten Ende-Button',
    '- **/arbeitszeit status** · zeigt deine letzten gespeicherten Arbeitszeiten',
    '- **/arbeitszeit nachtragen** · ergänzt oder korrigiert einen vergangenen Arbeitstag',
    '',
    'Bei **/arbeitszeit nachtragen** ist das angegebene Datum immer das Startdatum.',
    'Ist die Ende-Uhrzeit kleiner oder gleich der Start-Uhrzeit, versteht der Bot das Ende automatisch als **Folgetag**. Beispiel: Start 20:00, Ende 01:15 bedeutet Ende am nächsten Kalendertag.',
    'Nachgetragene Zeiten können als **genau** oder **geschätzt** gekennzeichnet werden.',
    'Für alte Dailies ohne gespeicherte Arbeitszeit werden keine Zeiten erfunden.',
    '',
    '## Arbeiten über 23:00 Uhr',
    'Eine vor dem Shutdown gestartete Arbeitszeit bleibt persistent gespeichert.',
    'Wenn der Bot am nächsten Morgen erkennt, dass eine ältere Arbeitszeit noch kein Ende hat, pingt er die betreffende Person im Scrum-Status-Channel und fordert einen Nachtrag an.',
    'Der Ping erfolgt bewusst **nicht** im Zeiterfassungs-Channel, damit dieser sauber bleibt.',
    'Eine Endzeit nach Mitternacht wird beim Nachtragen korrekt dem Folgetag zugeordnet, der Arbeitstag selbst bleibt aber unter seinem Startdatum dokumentiert.',
    '',
    '## Push-Erinnerung',
    'Wenn im Daily **Noch zu pushen: Ja** angegeben wurde, prüft der Bot regelmäßig den dokumentierten Status. Nach ungefähr 6 Stunden kann einmalig eine Erinnerung im Daily-Thread erscheinen.',
    'Der Bot kontrolliert **nicht GitHub** und hat keinen Zugriff auf das private Hauptprojekt-Repository. Die Push-Funktion ist eine Dokumentations- und Erinnerungshilfe, keine Repository-Prüfung.',
    '',
    '## Wochenbericht',
    'Der automatische Wochenbericht wird **freitags ab 14:00 Uhr alle 30 Minuten** geprüft.',
    'Er wird erst erzeugt, wenn der Freitag für alle drei Teammitglieder abgeschlossen dokumentiert ist:',
    '- Daily **und** abgeschlossene Arbeitszeit',
    '- oder gültige Abmeldung',
    '',
    'Wenn eine Freitags-Arbeitszeit wegen Arbeit nach 23:00 Uhr noch offen ist, prüft der Bot **samstags zwischen ungefähr 08:00 und 22:30 Uhr alle 30 Minuten erneut**. Dadurch kann der Wochenbericht nach einem morgendlichen Endzeit-Nachtrag automatisch fertiggestellt werden.',
    'Pro Kalenderwoche wird dabei nur ein automatischer finaler Wochenbericht erzeugt.',
    '',
    'Der Bericht verwendet alte und neue Discord-Dailies ab dem Beginn der Erfassung. Alte Dailies ohne Arbeitszeiterfassung bleiben erhalten und werden als Altbestand ohne erfundene Zeit gekennzeichnet.',
    'Der Bericht orientiert sich an den bib-Anforderungen und enthält, soweit tatsächlich dokumentiert: individuelle Tätigkeiten und Arbeitszeiten, Meetings, Entscheidungen, Blocker, Abwesenheiten, Dokumentationsstatus und nächste Schritte.',
    'Meeting-Protokolle, Aufgaben und Entscheidungen erscheinen nur, wenn dazu wirklich Daten vorhanden sind.',
    'Zu jedem erzeugten Wochenbericht erstellt der Bot **eine Markdown-Datei und eine PDF-Datei**. Die PDF verwendet das hinterlegte bib-Logo.',
    '',
    '**Wochenbericht-Befehle:**',
    '- **/wochenbericht vorschau** · aktuellen Bericht privat ansehen',
    '- **/wochenbericht erstellen** · Bericht manuell erzeugen',
    '- **/wochenbericht freigeben** · neuesten Bericht als freigegeben markieren',
    '- **/wochenbericht export** · aktuellen Bericht als Markdown- und PDF-Datei exportieren',
    '',
    'Wichtige Wochenberichte sollen vor der Weitergabe an den PbD kurz geprüft werden. Der Bot unterstützt die Dokumentation, ersetzt aber nicht die Verantwortung des Teams für richtige Angaben.',
    '',
    '## Meetings',
    `Neue Meetings werden mit **/meeting** in <#${config.meetingCreateChannelId}> erstellt.`,
    'Als Ort stehen **Discord Voice**, **Alfaview** oder **Anderer Link** wie Microsoft Teams zur Verfügung.',
    'Titel, Datum, Uhrzeit, Dauer und Agenda werden dokumentiert.',
    'Vergangene Meetings können mit **/meeting-nachtragen** ergänzt werden.',
    'Nachgetragene Meetings werden im Meeting-Channel sichtbar dokumentiert und zusätzlich persistent in der Meeting-Historie gespeichert, sodass sie im passenden Wochenbericht erscheinen können.',
    'Unter einem Meeting stehen die Aktionen **Protokoll**, **Aufgabe** und **Entscheidung** zur Verfügung. Diese Inhalte können in den Wochenbericht einfließen.',
    '',
    '## Freiwilliges Aufgabenboard',
    '**/task** verwaltet das optionale To-Do / Doing / Done-Board.',
    '- **/task add** · Aufgabe anlegen',
    '- **/task board** · komplettes Board anzeigen',
    '- **/task meine** · eigene offene Aufgaben anzeigen',
    '- **/task move** · eigene Aufgabe verschieben',
    '- **/task fortschritt** · freiwilligen Fortschritt von 0 bis 100 % setzen',
    '- **/task löschen** · eigene Aufgabe aus dem Board entfernen',
    '',
    'Nach einem Daily können die unter „Heute“ eingetragenen Punkte freiwillig ins Board übernommen werden. Das Board ist keine Grundlage zur Berechnung offizieller Arbeitsanteile.',
    '',
    '## Blocker',
    'Blocker aus Dailies können als offene Blocker dokumentiert werden.',
    '- **/blocker add** · Blocker manuell erfassen',
    '- **/blocker offen** · offene Blocker anzeigen',
    '- **/blocker lösen** · eigenen Blocker als gelöst markieren',
    '',
    '## Entscheidungen',
    '- **/entscheidung add** · wichtige Projektentscheidung mit optionaler Begründung dokumentieren',
    '- **/entscheidung liste** · dokumentierte Entscheidungen anzeigen',
    '',
    '## Status und Hilfe',
    '- **/scrum status** · heutigen Daily-/Abmeldestatus des Teams anzeigen',
    '- **/scrum heute** · Alias für den heutigen Scrum-Status',
    '- **/status** · technische Bot- und Channel-Konfiguration prüfen',
    '- **/info** · diese feste Info-Seite bewusst neu veröffentlichen bzw. aktualisieren',
    '- **/test** · geplante Bot-Aktionen manuell testen; nur für Personen mit „Server verwalten“',
    '',
    '## Info-Seite · bewusst nur manuell',
    '**Diese Info-Seite wird niemals automatisch beim morgendlichen Bot-Start oder durch einen Zeitplan neu veröffentlicht.**',
    'Sie bleibt unverändert im Info-Channel stehen. Nur wenn wir Regeln oder Bot-Funktionen gemeinsam ändern, wird sie anschließend bewusst mit **/info** neu erzeugt bzw. aktualisiert.',
    'Der normale tägliche Botstart verändert diese Seite nicht.',
    '',
    '## Daten und Neustarts',
    'Abgesendete Dailies und Abmeldungen liegen in Discord.',
    'Projektstatus, Arbeitszeiten und Meeting-Historie werden zusätzlich persistent gespeichert. Der tägliche Shutdown löscht diese Daten nicht.',
    'Der Bot speichert keine Prüfkopie des privaten Hauptprojekt-Repositories und überwacht dessen Git-Zustand nicht.',
    '',
    `_Reguläre Bot-Auswertung ab ${config.trackingStartDate}. Schulische Fristen und Vorgaben bitte zusätzlich nach aktuellem bib-Intranet und den Absprachen mit dem PbD prüfen._`
  ].join('\n');
}
