import { config } from './config.js';

// Wird nur manuell mit /info veröffentlicht. Leerzeilen trennen die Discord-Nachrichten,
// deshalb stehen sie nur zwischen Abschnitten.
export function botInfoPageText(): string {
  const timeChannel = `<#${config.timeTrackingChannelId}>`;
  const meetingChannel = `<#${config.meetingCreateChannelId}>`;
  const weeklyForum = `<#${config.weeklyForumId}>`;

  return [
    '# Scrum Master Bot · Projektübersicht',
    'Der Bot hilft uns bei Daily, Arbeitszeit, Meetings und dem Wochenbericht für den PbD. Das Wichtigste steht oben.',
    '',
    '## So läuft ein Projekttag (Mo–Fr)',
    '1. **/daily** · vor Arbeitsbeginn ausfüllen (4 kurze Fragen). Kannst du heute nicht arbeiten, wähle dort **Nein, abmelden**.',
    `2. **Start** in ${timeChannel} drücken. Für Pausen **Pause** und danach **🟠 Weitermachen**.`,
    '3. **Ende** drücken, wenn du für heute fertig bist.',
    '> **Daily zuerst, dann arbeiten.** Am Wochenende ist kein Daily nötig.',
    '',
    '## Die wichtigsten Befehle',
    '- **/daily** · Daily ausfüllen oder für heute abmelden',
    '- **/daily-bearbeiten** · heutiges Daily korrigieren',
    '- **/arbeitszeit nachtragen** · vergessene oder falsche Arbeitszeit eintragen',
    '- **/blocker offen** · offene Blocker mit ihrer ID ansehen',
    '- **/blocker lösen** · eigenen Blocker als behoben markieren',
    `- **/meeting** · Meeting planen (nur in ${meetingChannel})`,
    '- **/wochenbericht export** · aktuellen Wochenbericht privat als PDF und Markdown',
    '',
    '## Alle weiteren Befehle',
    '**Arbeitszeit**',
    '- **/arbeitszeit status** · deine zuletzt gespeicherten Zeiten',
    '**Meetings**',
    '- **/meeting-nachtragen** · vergangenes Meeting nachträglich dokumentieren',
    '- Buttons unter jeder Meeting-Karte: **Protokoll**, **Aufgabe**, **Entscheidung**',
    '**Blocker und Entscheidungen**',
    '- **/blocker add** · Blocker erfassen, der nicht im Daily steht',
    '- **/entscheidung add** · wichtige Projektentscheidung mit Begründung festhalten',
    '- **/entscheidung liste** · bisherige Entscheidungen mit ID ansehen',
    '- **/entscheidung löschen** · Entscheidung entfernen (ID aus der Liste)',
    '**Wochenbericht**',
    '- **/wochenbericht vorschau** · Text des aktuellen Berichts privat ansehen',
    '- **/wochenbericht erstellen** · Bericht sofort im Wochenbericht-Forum anlegen',
    '- **/wochenbericht freigeben** · „Freigegeben von …“ in den neuesten Bericht schreiben',
    '**Aufgabenboard (freiwillig)**',
    '- **/task add** · **/task board** · **/task meine** · **/task move** · **/task fortschritt** · **/task löschen**',
    '**Team und Technik**',
    '- **/scrum status** · wer heute schon ein Daily oder eine Abmeldung hat',
    '- **/status** · prüft Bot und Channels',
    '- **/info** · diese Seite neu veröffentlichen (nur hier im Info-Channel)',
    '- **/test** · geplante Bot-Aktionen testen (nur mit „Server verwalten“)',
    '',
    '## Gut zu wissen',
    '**Arbeitszeit nachtragen**',
    '- Das Datum ist immer der Tag, an dem du angefangen hast.',
    '- Ende nach Mitternacht? Einfach z. B. Start `20:00` und Ende `01:15` eingeben.',
    '- Der Bot ist nachts aus (23:00 bis ca. 08:05). Wer länger arbeitet, trägt das Ende am nächsten Morgen nach. Der Bot erinnert um 09:00 daran.',
    '**Abmelden**',
    '- Gründe: Krankheit, Termin oder Anderes. Die Abmeldung ersetzt das Daily, Erinnerungen kommen dann nicht mehr.',
    '- Bei Krankheit zusätzlich vor 08:00 im bib-Intranet krankmelden: https://intranet.bib.de/tiki-index.php?page=welcome',
    '**Blocker**',
    '- Blocker aus dem Daily landen automatisch in der Blocker-Liste.',
    '- Im Wochenbericht stehen sie als **offen**, bis sie mit **/blocker lösen** behoben sind.',
    '',
    '## Was der Bot automatisch macht',
    '- **09:00** (Mo–Fr) · Daily-Runde öffnen',
    '- **09:00** (Mo–Sa) · an Arbeitszeiten ohne Ende vom Vortag erinnern',
    '- **15:00** und **20:00** · Erinnerung, wenn Daily oder Abmeldung fehlt',
    '- **morgens** (Di–Sa) · fehlende Dailies vom Vortag dokumentieren; nach 2 Tagen in Folge wird Inaktivität vermerkt',
    `- **ca. ${config.pushReminderAfterHours} h nach dem Daily** · einmalige Push-Erinnerung bei „Noch zu pushen: Ja“ (der Bot prüft GitHub nicht)`,
    '- **Freitag ab 14:00** · Wochenbericht, sobald alle fertig sind (Daily und Ende oder Abmeldung)',
    '- **Samstag 12:00** · Wochenbericht in jedem Fall, falls noch keiner existiert',
    `> Der Wochenbericht (PDF und Markdown) erscheint in ${weeklyForum}. Bitte vor dem Weiterleiten an den PbD kurz prüfen.`,
    '',
    '## Schule · das Wichtigste',
    '- **Wochenbericht** jeden Freitag an den PbD: Arbeitszeiten und Tätigkeiten jedes Teammitglieds einzeln.',
    '- **Krank:** am 1. Tag vor Arbeitsbeginn beim Unternehmen melden und dem PbD mailen. Ab dem 3. Fehltag Arbeitsunfähigkeitsbescheinigung an PbD und Unternehmen.',
    '- **Probleme** früh mit dem PbD besprechen. Änderungen am Projektauftrag sofort melden.',
    '- **Dokumentation** aus 6 Teilen: Pflichtenheft, Entwurf, Implementierung, Test, Benutzerdoku, Installationshandbuch. DIN A4, Deckblatt, Bundsteg mindestens 2 cm.',
    '- **Letzte Projektwoche:** Präsentation im Unternehmen, PbD einladen.',
    '- **Letzter Projekttag:** Gesamtdokumentation und Formular „Aufgabenverteilung und Zeugnistext“ abgeben (Zeugnistext max. 160 Zeichen).',
    '- **Projektende:** Unterlagen, Hardware, Schlüssel, Zugänge und Passwörter übergeben. Beurteilungsbogen ans Unternehmen geben.',
    '- **Projektjahrbuch:** Kurzfassung und 2 Bilder einreichen, Veröffentlichung mit dem Unternehmen abstimmen.',
    '- **Bewertung** (200 Punkte): Produkt 50 % · Dokumentation 20 % · Präsentation 15 % · Formales 15 % (u. a. pünktliche Wochenberichte).',
    '-# Im Zweifel gelten das bib-Intranet und die Absprachen mit dem PbD.'
  ].join('\n');
}
